releaseType: java-yoshi
bumpMinorPreMajor: true
branches:
  - releaseType: java-lts
    bumpMinorPreMajor: true
    branch: 1.63.0-sp
  - releaseType: java-lts
    bumpMinorPreMajor: true
    branch: 1.64.0-sp
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    branch: java7