releaseType: java-yoshi
bumpMinorPreMajor: true
handleGHRelease: true
branches:
  - releaseType: java-backport
    bumpMinorPreMajor: true
    handleGHRelease: true
    branch: 2.16.x
  - releaseType: java-backport
    bumpMinorPreMajor: true
    handleGHRelease: true
    branch: 2.19.x
