sudo: false
dist: precise
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
install: ./gradlew assemble
script: ./gradlew build install
after_success:
  - bash <(curl -s https://codecov.io/bash)
