sudo: false
dist: precise
language: java
addons:
  # https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
  hosts:
    - fake-hostname-to-work-around-travis-bug
  hostname: fake-hostname-to-work-around-travis-bug
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
install: ./gradlew assemble
script: ./gradlew build install
after_success:
  - bash <(curl -s https://codecov.io/bash)
