sudo: false
dist: trusty
language: java
addons:
  # https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
  hosts:
    - fake-hostname-to-work-around-travis-bug
  hostname: fake-hostname-to-work-around-travis-bug
jdk:
  - openjdk8
  - openjdk7

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.5.0/bazel_3.5.0-linux-x86_64.deb
  - wget https://github.com/bazelbuild/bazel/releases/download/3.5.0/bazel_3.5.0-linux-x86_64.deb.sha256
  - sha256sum -c bazel_3.5.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_3.5.0-linux-x86_64.deb

install: ./gradlew assemble

# The Bazel flags below are the best we can do to optimize build speed, since caching on Travis
# is suboptimal for various reasons (see https://kevin.burke.dev/kevin/bazel-tests-on-travis-ci/).
script:
  - ./gradlew build install
  - bazel --batch test //... --noshow_progress --test_output=errors
after_success:
  - bash <(curl -s https://codecov.io/bash)
