codecov:
    coverage:
        status:
            project: true
            patch: true
            changes: false

    comment:
        layout: "header, diff, changes, suggestions"
        behavior: default
