/*
 * Copyright 2019 Google LLC
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google LLC nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.google.api.gax.batching.v2;

import com.google.api.core.SettableApiFuture;
import java.util.List;

/**
 * An adapter that packs and unpacks the elements in and out of batch requests and responses.
 *
 * <p>This interface should be implemented by either a service specific client or autogenerated by
 * gapic-generator.
 *
 * <p>Example implementation:
 *
 * <pre>{@code
 * class ListDescriptor implements BatchingDescriptor<String, List<String>, String, List<String>> {
 *
 *   RequestBuilder<String, List<String>> newRequestBuilder(List<String> prototype) {
 *     return new RequestBuilder<String, List<String>>() {
 *
 *       RequestBuilder<String, List<String>> add(String element) {
 *         list.add(element);
 *         return this;
 *       }
 *
 *       List<String> build() {
 *         return list.clone();
 *       }
 *     };
 *   }
 *
 *   void splitResponse(List<String> callableResponse, List<SettableApiFuture<String>> batch) {
 *     Iterator<String> respIt = callableResponse.iterator();
 *     Iterator<SettableApiFuture<String>> it = batch.iterator();
 *
 *     while (respIt.hasNext()) {
 *       it.next().set(respIt.next());
 *     }
 *   }
 *
 *   void splitException(Throwable throwable, List<SettableApiFuture<String>> batch) {
 *     for (SettableApiFuture<String> result : batch) {
 *       result.setException(throwable);
 *     }
 *   }
 *
 *   long countBytes(String element) {
 *     return element.length();
 *   }
 * }
 * }</pre>
 *
 * @param <RequestElementT> The request type to perform batching.
 * @param <RequestT> The request wrapper type which bundles {@link RequestElementT}.
 * @param <ResponseElementT> The response type of an entry object.
 * @param <ResponseT> The response wrapper type which bundles {@link ResponseElementT}.
 */
public interface BatchingDescriptor<RequestElementT, RequestT, ResponseElementT, ResponseT> {

  /**
   * Creates a new wrapper for the underlying request builder. It's used to pack the current batch
   * request with elements.
   */
  RequestBuilder<RequestElementT, RequestT> newRequestBuilder(RequestT prototype);

  /** Unpacks the batch response into individual elements results. */
  void splitResponse(ResponseT batchResponse, List<SettableApiFuture<ResponseElementT>> batch);

  /** Unpacks the batch response error into individual element errors. */
  void splitException(Throwable throwable, List<SettableApiFuture<ResponseElementT>> batch);

  /** Returns the size of the passed element object in bytes. */
  long countBytes(RequestElementT element);
}
