/*
 * Copyright 2019 Google LLC
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google LLC nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.google.api.gax.batching.v2;

import com.google.api.core.SettableApiFuture;
import java.util.List;

/**
 * This represents operations that transform elements/result data for batching purposes.
 *
 * <p>Implementations of BatchingDescriptor must guarantee that all methods are stateless and thread
 * safe. It will be autogenerated by the gapic-generator.
 */
public interface BatchingDescriptor<ElementT, ResultT, RequestT, ResponseT> {

  /**
   * Creates a new wrapper for the underlying request builder. It is used to abstract the underlying
   * request type.
   */
  RequestBuilder<ElementT, RequestT> newRequestBuilder(RequestT prototype);

  /**
   * Splits the response from a RPC into respective future of {@link ResultT} to mark them resolved.
   */
  void splitResponse(ResponseT batchResponse, List<SettableApiFuture<ResultT>> batch);

  /** Marks the {@link ResultT} with exception received while perform batching. */
  void splitException(Throwable throwable, List<SettableApiFuture<ResultT>> batch);

  /** Returns the size in bytes of passed element object. */
  long countBytes(ElementT element);
}
