'on':
  push:
    branches:
      - 2.19.x
  pull_request: null
name: downstream
jobs:
  graalvm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        graalvm:
          - 22.2.0
        java:
          - 11
          - 17
        repo:
          - orgpolicy
    steps:
      - uses: actions/checkout@v2
      - uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.1
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: ${{matrix.java}}
          graalvm-version: ${{matrix.graalvm}}
          native-image: true
      - run: java -version
      - run: sudo apt-get update -y
      - run: sudo apt-get install libxml2-utils
      - run: .kokoro/downstream-client-library-check.sh ${{matrix.repo}} graalvm
