on:
  push:
    branches:
    - main
  pull_request:

# Keeping this file separate as the dependencies check would use more
# repositories than needed this downstream check for GraalVM native image
# compilation.
name: downstream
jobs:
  # GraalVM job ensures the compatibility of GraaVM version
  graalvm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        graalvm: [22.1.0, 22.0.0.2, 21.3.2]
        java: [11, 17]
        repo:
        # GAPIC library that doesn't use a real GCP project in integration tests
        - orgpolicy
    steps:
    - uses: actions/checkout@v2
    - uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.8.1
    - uses: ayltai/setup-graalvm@v1
      with:
        java-version: ${{matrix.java}}
        # When a new version of native-maven-plugin fails to run in a downstream
        # library, it's likely to be an incompatibility with the GraalVM version.
        # In that case, you need to upgrade the Docker container used in the
        # tests in the downstream repositories (not just this value below).
        # Example: https://github.com/googleapis/testing-infra-docker/pull/195
        graalvm-version: ${{matrix.graalvm}}
        native-image: true
    - run: java -version
    - run: sudo apt-get update -y
    - run: sudo apt-get install libxml2-utils
    - run: .kokoro/downstream-client-library-check.sh ${{matrix.repo}} graalvm